### PR TITLE
Allow admins to create, delete and deactivate users

### LINKED ISSUE #115: Ajouter une fonction d'administration des utilisateurs
Cette fonction doit être accessible uniquement par les administrateurs.
Elle doit permettre de modifier des utilisateurs existants, de les désactiver, renommer, changer le mot de passe. Elle doit aussi permettre d'ajouter un nouvel utilisateur.

### PR DESCRIPTION
**Pull request by MestourBS**
- Closes #115
- Adds an admin menu for editing users
- Changes `t_user` `is_active` to `is_inactive` for soft delete key

### CODE REVIEW

**Comment by MestourBS** [comment]
Comme j'utilise `$soft_delete_key` et `$soft_delete` dans `user_model`, c'est plus clair que le champ passe à vrai quand l'user est inactif.

**Comment by DidierViret** [comment]
A PARTIR DE MAINTENANT, MERCI DE NOMMER SYSTÉMATIQUEMENT LES SOFT_DELETE_KEY "is_deleted".

**Comment by DidierViret** [comment]
Errors to fix in users admin :
- Cannot active an unactive user
- Cannot modify an unactive user

**Comment by DidierViret** [comment]
JE CONTREDIS MON COMMENTAIRE PRÉCÉDENT (QUE J'AI EFFACÉ) :
POUR LES SOFT_DELETE_KEY, MERCI D'UTILISER COMME NOM DE CHAMP "Archive".

**Pull request merged**
